// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

import { offlineDB } from '@/lib/offline-db';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Fetch Wrapper offline
const customOfflineFetch = async (url: RequestInfo | URL, options?: RequestInit): Promise<Response> => {
  const method = options?.method || 'GET';
  
  // Only intercept mutations if we are likely offline
  // We check navigator.onLine but also catch actual network errors
  if (method !== 'GET' && !window.navigator.onLine) {
    console.log('[Offline] Intercepting request (Offline detected):', method, url);
    return enqueueAndMock(url, options);
  }

  try {
    const response = await fetch(url, options);
    return response;
  } catch (error) {
    // If it's a network error and not a GET, enqueue it
    if (method !== 'GET' && error instanceof TypeError && error.message === 'Failed to fetch') {
      console.log('[Offline] Network error detected, enqueuing mutation:', method, url);
      return enqueueAndMock(url, options);
    }
    throw error;
  }
};

const enqueueAndMock = async (url: RequestInfo | URL, options?: RequestInit): Promise<Response> => {
  const method = options?.method || 'POST';
  const body = options?.body ? options.body.toString() : null;
  const urlString = url.toString();
  
  // Save to IndexedDB
  await offlineDB.enqueueRequest({
    url: urlString,
    method,
    body,
    headers: {}, 
  });

  return new Response(JSON.stringify([{ id: 'offline-pending', status: 'queued' }]), { 
    status: 200, 
    headers: { 'Content-Type': 'application/json' } 
  });
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: customOfflineFetch
  }
});