// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

import { offlineDB } from '@/lib/offline-db';
import { IS_NATIVE_APP } from '@/lib/platform';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Fetch Wrapper offline
const customOfflineFetch = async (url: RequestInfo | URL, options?: RequestInit): Promise<Response> => {
  const method = options?.method || 'GET';
  const urlString = url.toString();

  // If we know we're offline and it's a mutation, enqueue immediately
  if (method !== 'GET' && !window.navigator.onLine) {
    console.log('[Offline] Enfileirando mutação offline:', method, urlString);
    return enqueueAndMock(url, options);
  }

  try {
    const response = await fetch(url, options);
    return response;
  } catch (error) {
    // Network error caught - we're actually offline
    if (error instanceof TypeError) {
      // For mutations: save to queue for later sync
      if (method !== 'GET') {
        console.log('[Offline] Erro de rede, enfileirando mutação:', method, urlString);
        return enqueueAndMock(url, options);
      }

      // For GETs on native app: return empty response so TanStack Query 
      // can fall back to its persisted cache instead of crashing
      if (IS_NATIVE_APP) {
        console.log('[Offline] Erro de rede em GET, retornando resposta vazia para uso do cache:', urlString);
        return new Response(JSON.stringify([]), {
          status: 200,
          headers: { 'Content-Type': 'application/json' }
        });
      }
    }
    throw error;
  }
};

const enqueueAndMock = async (url: RequestInfo | URL, options?: RequestInit): Promise<Response> => {
  const method = options?.method || 'POST';
  const body = options?.body ? options.body.toString() : null;
  const urlString = url.toString();
  
  await offlineDB.enqueueRequest({
    url: urlString,
    method,
    body,
    headers: {},
  });

  return new Response(JSON.stringify([{ id: 'offline-pending', status: 'queued' }]), { 
    status: 200, 
    headers: { 'Content-Type': 'application/json' } 
  });
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: customOfflineFetch
  }
});